- name: create ec2 and route53 records 
  hosts: local 
  connection: local 
  vars: 
    subnet_id: subnet-057dac3e025a3d9c6
    sg_id: sg-08eed4ca0fd852a9e 
    ami_id: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
    zone: dev.divyavutakanti.com

  tasks:
  - name: install python librabries
    ansible.builtin.pip:
      name: 
      - botocore
      - boto3
      executable:3.9
  - name: create ec2 instance 
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id:  "{{ subnet_id }}"
      instance_type: "t3.micro" 
      security_group: "{{ sg_id }}" 
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}" 
    register: ec2_instances_info

  - name: print the output 
    ansible.builtin.debug: 
      msg: "{{ ec2_instances_info }}" 

  - name: create route 53 private records
    amazon.aws.route53: 
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone}}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances_info.results }}"
  
  - name: create r53 for public records
    amazon.aws.route53: 
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances_info.results }}"
    when: item.item == "frontend" 