- name: configure backend server 
  hosts: backend
  vars: 
    mysql_rootpass: ExpenseApp@1
    mysql_hostlogin: mysql.dev.divyavutakanti.com
    packages: 
    - nodejs
    - mysql 
  become: yes 
  roles:
  - backend